package config

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/sirupsen/logrus"
	"gopkg.in/yaml.v2"
)

// Config represents the application configuration
type Config struct {
	Database DatabaseConfig `yaml:"database" json:"database"`
	Migration MigrationConfig `yaml:"migration" json:"migration"`
	Logging   LoggingConfig   `yaml:"logging" json:"logging"`
	UI        UIConfig        `yaml:"ui" json:"ui"`
}

// DatabaseConfig holds database-related settings
type DatabaseConfig struct {
	DefaultVendor    string            `yaml:"defaultVendor" json:"defaultVendor"`
	DefaultHost      string            `yaml:"defaultHost" json:"defaultHost"`
	DefaultPorts     map[string]string `yaml:"defaultPorts" json:"defaultPorts"`
	ConnectionPool   PoolConfig        `yaml:"connectionPool" json:"connectionPool"`
	ConnectionTimeout int              `yaml:"connectionTimeout" json:"connectionTimeout"` // seconds
}

// PoolConfig holds connection pool settings
type PoolConfig struct {
	MaxConnections int `yaml:"maxConnections" json:"maxConnections"`
	MaxIdleTime    int `yaml:"maxIdleTime" json:"maxIdleTime"`       // seconds
	ConnMaxLifetime int `yaml:"connMaxLifetime" json:"connMaxLifetime"` // seconds
}

// MigrationConfig holds migration-related settings
type MigrationConfig struct {
	DefaultBatchSize    int               `yaml:"defaultBatchSize" json:"defaultBatchSize"`
	EnableTransactions  bool              `yaml:"enableTransactions" json:"enableTransactions"`
	EnableProgress      bool              `yaml:"enableProgress" json:"enableProgress"`
	AutoGenerateDump    bool              `yaml:"autoGenerateDump" json:"autoGenerateDump"`
	DefaultDumpPath     string            `yaml:"defaultDumpPath" json:"defaultDumpPath"`
	EnableCheckpoints   bool              `yaml:"enableCheckpoints" json:"enableCheckpoints"`
	ValidationRules     ValidationConfig  `yaml:"validationRules" json:"validationRules"`
	CommonMappings      map[string]string `yaml:"commonMappings" json:"commonMappings"`
}

// ValidationConfig holds data validation settings
type ValidationConfig struct {
	CheckDataTypes      bool `yaml:"checkDataTypes" json:"checkDataTypes"`
	CheckNullConstraints bool `yaml:"checkNullConstraints" json:"checkNullConstraints"`
	CheckForeignKeys    bool `yaml:"checkForeignKeys" json:"checkForeignKeys"`
	StrictMode          bool `yaml:"strictMode" json:"strictMode"`
}

// LoggingConfig holds logging settings
type LoggingConfig struct {
	Level            string `yaml:"level" json:"level"`
	EnableFileOutput bool   `yaml:"enableFileOutput" json:"enableFileOutput"`
	LogFilePath      string `yaml:"logFilePath" json:"logFilePath"`
	MaxFileSize      int    `yaml:"maxFileSize" json:"maxFileSize"` // MB
	MaxBackups       int    `yaml:"maxBackups" json:"maxBackups"`
	EnableJSON       bool   `yaml:"enableJSON" json:"enableJSON"`
	EnableConsole    bool   `yaml:"enableConsole" json:"enableConsole"`
}

// UIConfig holds UI-related settings
type UIConfig struct {
	ShowProgress         bool   `yaml:"showProgress" json:"showProgress"`
	EnableHelp           bool   `yaml:"enableHelp" json:"enableHelp"`
	ConfirmationRequired bool   `yaml:"confirmationRequired" json:"confirmationRequired"`
	Theme                string `yaml:"theme" json:"theme"`
	EnableColors         bool   `yaml:"enableColors" json:"enableColors"`
}

// DefaultConfig returns a configuration with sensible defaults
func DefaultConfig() *Config {
	return &Config{
		Database: DatabaseConfig{
			DefaultVendor: "mysql",
			DefaultHost:   "localhost",
			DefaultPorts: map[string]string{
				"mysql":  "3306",
				"oracle": "1521",
			},
			ConnectionPool: PoolConfig{
				MaxConnections:   10,
				MaxIdleTime:     300, // 5 minutes
				ConnMaxLifetime: 3600, // 1 hour
			},
			ConnectionTimeout: 30, // 30 seconds
		},
		Migration: MigrationConfig{
			DefaultBatchSize:   1000,
			EnableTransactions: true,
			EnableProgress:     true,
			AutoGenerateDump:   false,
			DefaultDumpPath:    "./migration_dump.sql",
			EnableCheckpoints:  false,
			ValidationRules: ValidationConfig{
				CheckDataTypes:       true,
				CheckNullConstraints: true,
				CheckForeignKeys:     false,
				StrictMode:          false,
			},
			CommonMappings: map[string]string{
				"id":         "id",
				"user_id":    "user_id",
				"name":       "name",
				"email":      "email",
				"created_at": "created_at",
				"updated_at": "updated_at",
			},
		},
		Logging: LoggingConfig{
			Level:            "info",
			EnableFileOutput: true,
			LogFilePath:      "./logs/dbcli.log",
			MaxFileSize:      100, // 100MB
			MaxBackups:       5,
			EnableJSON:       true,
			EnableConsole:    true,
		},
		UI: UIConfig{
			ShowProgress:         true,
			EnableHelp:           true,
			ConfirmationRequired: true,
			Theme:               "default",
			EnableColors:        true,
		},
	}
}

// LoadConfig loads configuration from file, with fallback to defaults
func LoadConfig(configPath string) (*Config, error) {
	// Start with default config
	config := DefaultConfig()

	// If no config file specified, look for common locations
	if configPath == "" {
		configPath = findConfigFile()
	}

	// If config file exists, load it
	if configPath != "" && fileExists(configPath) {
		logrus.WithField("configPath", configPath).Info("Loading configuration file")
		
		data, err := os.ReadFile(configPath)
		if err != nil {
			return nil, fmt.Errorf("failed to read config file: %v", err)
		}

		// Determine file format and unmarshal
		if filepath.Ext(configPath) == ".yaml" || filepath.Ext(configPath) == ".yml" {
			if err := yaml.Unmarshal(data, config); err != nil {
				return nil, fmt.Errorf("failed to parse YAML config: %v", err)
			}
		} else {
			if err := json.Unmarshal(data, config); err != nil {
				return nil, fmt.Errorf("failed to parse JSON config: %v", err)
			}
		}

		logrus.Info("Configuration loaded successfully")
	} else {
		logrus.Info("No config file found, using defaults")
	}

	// Validate configuration
	if err := config.Validate(); err != nil {
		return nil, fmt.Errorf("invalid configuration: %v", err)
	}

	return config, nil
}

// SaveConfig saves the current configuration to file
func (c *Config) SaveConfig(configPath string) error {
	// Ensure directory exists
	dir := filepath.Dir(configPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %v", err)
	}

	var data []byte
	var err error

	// Determine file format and marshal
	if filepath.Ext(configPath) == ".yaml" || filepath.Ext(configPath) == ".yml" {
		data, err = yaml.Marshal(c)
		if err != nil {
			return fmt.Errorf("failed to marshal YAML config: %v", err)
		}
	} else {
		data, err = json.MarshalIndent(c, "", "  ")
		if err != nil {
			return fmt.Errorf("failed to marshal JSON config: %v", err)
		}
	}

	if err := os.WriteFile(configPath, data, 0644); err != nil {
		return fmt.Errorf("failed to write config file: %v", err)
	}

	logrus.WithField("configPath", configPath).Info("Configuration saved successfully")
	return nil
}

// Validate validates the configuration values
func (c *Config) Validate() error {
	// Validate batch size
	if c.Migration.DefaultBatchSize <= 0 {
		return fmt.Errorf("migration batch size must be positive")
	}

	// Validate connection pool settings
	if c.Database.ConnectionPool.MaxConnections <= 0 {
		return fmt.Errorf("max connections must be positive")
	}

	// Validate log level
	if _, err := logrus.ParseLevel(c.Logging.Level); err != nil {
		return fmt.Errorf("invalid log level: %v", err)
	}

	// Validate file paths
	if c.Logging.EnableFileOutput && c.Logging.LogFilePath == "" {
		return fmt.Errorf("log file path required when file output is enabled")
	}

	return nil
}

// findConfigFile looks for config files in common locations
func findConfigFile() string {
	configFiles := []string{
		"./config.yaml",
		"./config.yml",
		"./config.json",
		"./dbcli.yaml",
		"./dbcli.yml",
		"./dbcli.json",
		"~/.dbcli/config.yaml",
		"~/.dbcli/config.yml",
		"~/.dbcli/config.json",
	}

	for _, path := range configFiles {
		if fileExists(path) {
			return path
		}
	}

	return ""
}

// fileExists checks if a file exists
func fileExists(path string) bool {
	if path == "" {
		return false
	}
	
	// Expand home directory
	if path[0] == '~' {
		home, err := os.UserHomeDir()
		if err == nil {
			path = filepath.Join(home, path[1:])
		}
	}

	_, err := os.Stat(path)
	return !os.IsNotExist(err)
}
